### PR TITLE
touch(nil) throws INJECT_EVENTS permission

### PR DESCRIPTION
**Pull request by rajdeepv**
touch(some_operation_which_results_in_nil_instead_of_valid_query_result) throws RuntimeError  
eg. touch(nil)  
RuntimeError: Failed to perform gesture. java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission  
Throwing more user-friendly exception in case query_string is nil.

### CODE REVIEW

**Comment by TobiasRoikjer** [comment]
@rajdeepv `touch(nil, offset: {x: ..., y: ...})` is currently a valid use case

**Comment by rajdeepv** [comment]
@TobiasRoikjer Thanks. I did not consider the case, sorry.

Should I add a check in touch method with offset? or if you feel its fine to leave it, this can be closed
Thanks

**Comment by TobiasRoikjer** [comment]
@rajdeepv If you add a check to see if *options* are nil or an empty map as well, I will merge this :)

**Comment by rajdeepv** [comment]
@TobiasRoikjer I have made the change for touch method because I think other gestures might work with nil query string.
Thanks.

**Pull request merged**
