### PR TITLE
Add an action to retrieve the internationalized value of a string id

### PR DESCRIPTION
**Pull request by ldavin**
Hi,

I've added an action to retrieve the value of a internationalized string in the ruby API.
I had a strong need for such an action for the application I'm working on, and I'm sure it can be useful to others.

Louis

### CODE REVIEW

**Comment by TobiasRoikjer** [comment]
@ldavin we should add a Ruby wrapper for each action. This PR seems sound.

**Comment by sapieneptus** [comment]
@TobiasRoikjer If this looks ok and builds (and works), why don't we merge it and make an issue for the Ruby client?

**Comment by TobiasRoikjer** [comment]
@sapieneptus Seems good to me.

**Comment by sapieneptus** [comment]
I'm going to close this and port it over to https://www.github.com/calabash/calabash-android-server - after we do some integration tests, we can merge it. 

CC: @ldavin

**Pull request closed without merging**
