### PR TITLE
Update project and documentation

### PR DESCRIPTION
**Pull request by friederbluemle**
This PR fixes all whitespace errors in the repo. It also updates the README.md file to be more consistent with `calabash-ios`. There is a newly added build status indicator from TravisCI, and a nicer looking tree structure for the Cucumber skeleton.

<sub><sup>Please NO GitHub rebase/squash merges. If you'd like me to combine some or all of the commits, please let me know, and I will update my branch. Thank you.</sup></sub>

### CODE REVIEW

**Comment by jmoody** [comment]
@friederbluemle 

Thanks for the pull request. 

I will discuss with Tobias, but I am fairly certain we are not interested in the whitespace change commit.  It touches too many files and adds no feature-level value.  We are aware there are many whitespace inconsistencies and have a policy of dealing with them on a case-by-case bases.

The README changes are interesting, but Tobias will have the final say.  Calabash Android and iOS have distinct cultures.

**Comment by friederbluemle** [comment]
@jmoody Thanks for the reply. The advantage of fixing *all* whitespace errors in a *single* commit is that future commits/PRs will not be polluted with line changes that are unrelated to the actual change. For example, it is (not easily) possible to save a file using `vim` and omit the newline character on the last line. If you mix whitespace changes with commits that change logic, it will be more difficult to review.
In the case of this PR, there is not really much to review for my first commit (everything was fixed using automated tools). The only actual change is contained in the second commit, which updates README.md.

**Comment by friederbluemle** [comment]
@jmoody Any updates on this? Would you prefer two separate PRs for the two commits? Do you want to keep the whitespace errors in the project? Is this project still active? Are the documentation updates OK? Or should I just close this PR? So many questions... ;) Thanks!

**Comment by jmoody** [comment]
I have reviewed this request.  We are not interested in this change set.

>  The advantage of fixing all whitespace errors in a single commit is that future commits/PRs will not be polluted with line changes that are unrelated to the actual change. 

As I mentioned, we have policy of dealing with them on a case-by-case basis.

> Is the project still active.

Yes.

> Are the documentation updates OK? 

As a whole, no.

The change logs should not be touched, nor should the change.txt.

The license file should not be touched and the license should not be added to the README.md

If you resubmit changes to the README.md, please create separate pull requests that address specific problems: "Capitalize Calabash", "Better tree structure for directory", "Clarify XXX", as examples.

**Comment by friederbluemle** [comment]
Thanks for the reply.

**Pull request closed without merging**
