### PR TITLE
Avoid poking around in structures which will change in Cucumber 2.0

### PR DESCRIPTION
**Pull request by olefriis**
Besides, remembering the actual feature instead of its name is a bit more robust.

### CODE REVIEW

**Comment by jmoody** [comment]
+1 @olefriis  Nice one.

**Comment by olefriis** [comment]
@TobiasRoikjer merge? As Cucumber 2.0 is actually out now, this one would be nice to have on master.

**Comment by jmoody** [comment]
@TobiasRoikjer @olefriis 

This is a first and necessary step for Cucumber 2.0.

Karl wants to support _both_ Cucumber 1.x and 2.x.

**Comment by olefriis** [comment]
@jmoody merge?

:-)

(I can merge myself, but it just... feels wrong to merge my own pull request... I don't know how you guys normally do in this repo.)

**Comment by jmoody** [comment]
@olefriis @TobiasRoikjer 

I would merge this myself, but I don't understand the changes well enough.

On the other hand, this is the _template_ for new projects so the consequences are quite low.  It is important that these changes get out to our users.  I think that calabash-android post or wiki page needs creating/updating. 

Since Tobias and I are (for practical purposes) solo programmers on the Calabash iOS and Calabash Android repos, we usually merge the PRs ourselves.  If the content is controversial, I usually ask Karl to review.  If the PR is conceptually difficult or includes a code-level detail that I am not sure about, I ask for a review from someone in the Aarhus office.

**Pull request merged**
