### PR TITLE
Remove retriable dependency

### PR DESCRIPTION
**Pull request by nicolai86**
Approach to remove the retrieable dependency.

Since our use case is quite simple, this simple approach ought to be enough.

See #743

### CODE REVIEW

**Comment by TobiasRoikjer** [comment]
@nicolai86 Thank you for this PR!

Please rename Calabash::Android::Retryable to Calabash::Android::Retry, and have the methods be static. I would like the API to be 
```ruby
Calabash::Android::Retry.retry ...
```

and not
```ruby
retry ...
```

**Comment by nicolai86** [comment]
@TobiasRoikjer thanks for the feedback. I've changed the PR accordingly

**Comment by TobiasRoikjer** [comment]
@nicolai86 Thank you!

**Comment by jmoody** [comment]
@nicolai86 Yes!  You made my vacation! Thanks!

**Comment by nicolai86** [comment]
@jmoody you're welcome. Looking forward to the next release so I can make my calabash test run on android :)

**Comment by zined** [comment]
:+1: :+1: :+1: :heart:

**Pull request merged**
