### PR TITLE
Feature/new android webview

### LINKED ISSUE #586: JsonMappingException: Can not deserialize instance of java.util.HashMap out of START_ARRAY
Operations on web view doesn't work if Android has latest 'Android System Webview' apk. Calabash-android report the following error,

W/System.err(14472): Caused by: java.lang.RuntimeException: sh.calaba.org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.util.HashMap out of START_ARRAY token
W/System.err(14472):  at [Source: java.io.StringReader@3c5095b7; line: 1, column: 1]
W/System.err(14472):    at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils$MapWebContainer.call(UIQueryUtils.java:337)
W/System.err(14472):    at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils$MapWebContainer.call(UIQueryUtils.java:290)
W/System.err(14472):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(14472):    at android.os.Handler.handleCallback(Handler.java:739)
W/System.err(14472):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(14472):    at android.os.Looper.loop(Looper.java:135)
W/System.err(14472):    at android.app.ActivityThread.main(ActivityThread.java:5312)
W/System.err(14472):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(14472):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(14472):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
W/System.err(14472):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
W/System.err(14472): Caused by: sh.calaba.org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.util.HashMap out of START_ARRAY token
W/System.err(14472):  at [Source: java.io.StringReader@3c5095b7; line: 1, column: 1]
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:219)
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:212)
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:246)
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2765)
W/System.err(14472):    at sh.calaba.org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1903)

the workaround for this error is downgrade the Android System Webview to the previous version.

1. Go to Settings -> App
2. Tap on Android System WebView
3. Tap on Uninstall Updates.

### PR DESCRIPTION
**Pull request by sapieneptus**
### Fixes #586 

- Removed calabash-js submodule (though I kept the path to calabash.js and set_text.js the same so no 
path references broke)
- Changed the way `getClientBoundingRect()` results are used. Apparently, the return value doesn't behave like a normal object, so you have to store the values explicitly. 

Note:
```

irb(main):030:0* evaluate_javascript "webView", "var bb = document.getElementById('username').getBoundingClientRect(); return bb.width"                                             
[                                                                                                                                                                                   
    [0] "192.234375"                                                                                                                                                                
]                                                                                                                                                                                   
irb(main):031:0> evaluate_javascript "webView", "var bb = document.getElementById('username').getBoundingClientRect(); return bb.height"                                            
[                                                                                                                                                                                   
    [0] "32.1875"                                                                                                                                                                   
]                                                                                                                                                                                   
irb(main):032:0> evaluate_javascript "webView", "var bb = document.getElementById('username').getBoundingClientRect(); return Object.keys(bb)"                                      
[                                                                                                                                                                                   
    [0] "[]"                              //See what I mean?                                                                                                                                         
]                                                                                                                                                                                   
irb(main):033:0> evaluate_javascript "webView", "var bb = document.getElementById('username').getBoundingClientRect(); return Object.keys(bb)[0]"                                  
[                                                                                                                                                                                  
    [0] "null"                                                                                                                                                                     
] 
```

### CODE REVIEW

**Comment by jmoody** [comment]
@sapieneptus 

Ah, finally, I found the associated pull request.

Can you comment on why we needed to remove this submodule?

This is a breaking change re: git.  I can't update my local repo.

**Comment by sapieneptus** [comment]
@jmoody I guess I don't understand why you can't update your local repo - the submodule was removed in the typical fashion, should exactly as before.

**Comment by jmoody** [comment]
@sapieneptus The pull / merge could not be performed because the calabash.js was previously part of another repo.  I am not surprised. :)

I think the only way to do this cleanly would have been to move the contents of the submodule to a new place in the repo and removed the submodule.

**Comment by jmoody** [comment]
@sapieneptus I just deleted my repo and started again.

**Comment by sapieneptus** [comment]
@jmoody When in doubt, turn it off and on again :p

**Pull request merged**
