### PR TITLE
Remove adb information output from run output

### PR DESCRIPTION
**Pull request by plus3x**

### CODE REVIEW

**Comment by TobiasRoikjer** [comment]
Will this work on Windows?

**Comment by plus3x** [comment]
@TobiasRoikjer https://support.microsoft.com/en-us/kb/110930 - seems like yes, but i can't check

**Comment by iMerica** [comment]
:+1: was just about to submit this :-)

**Comment by goughy000** [comment]
Would be great if it was configurable. We run our tests in a pipeline like I'm sure most people do and the more logging the better

**Comment by iMerica** [comment]
Is there anything pending on this pull request? I care a lot of about the signal/noise ratio on Cucumber results and the adb output really adds nothing.

**Comment by goughy000** [comment]
Should do this...
cmd << " 2>&1" unless (ARGV.include? "-v" or ARGV.include? "--verbose")

and the adb commands on lines 580 and 585 write to stderr so should have this fix

**Comment by iMerica** [comment]
I was able to workaround this issue by monkey patching `Calabash::Android::Operations`. You can add this to your `env.rb` file.

```ruby
require 'json'
require 'net/http'
require 'open-uri'
require 'rubygems'
require 'json'
require 'socket'
require 'timeout'
require 'calabash-android/gestures'
require 'calabash-android/helpers'
require 'calabash-android/environment_helpers'
require 'calabash-android/text_helpers'
require 'calabash-android/touch_helpers'
require 'calabash-android/wait_helpers'
require 'calabash-android/version'
require 'calabash-android/env'
require 'retriable'
require 'cucumber'
require 'date'
require 'time'

module Calabash
  module Android
    module Operations
      include Calabash::Android::EnvironmentHelpers
      include Calabash::Android::TextHelpers
      include Calabash::Android::TouchHelpers
      include Calabash::Android::WaitHelpers
      class Device
        attr_reader :app_path, :test_server_path, :serial, :server_port, :test_server_port
        def install_app(app_path)
          cmd = "#{adb_command} install \"#{app_path}\" 2>&1"
          log "Installing: #{app_path}"
          result = `#{cmd}`
          log result
          pn = package_name(app_path)
          succeeded = `#{adb_command} shell pm list packages`.lines.map{|line| line.chomp.sub("package:", "")}.include?(pn)

          unless succeeded
            ::Cucumber.wants_to_quit = true
            raise "#{pn} did not get installed. Reason: '#{result.lines.last.chomp}'. Aborting!"
          end
        end
      end
    end
  end
end
```

LOL

**Comment by TobiasRoikjer** [comment]
Some users may appreciate this information. In 2.0 we have way better detection of errors, and therefore hide this output.

**Pull request closed without merging**
