### PR TITLE
ClearText.java use editable.clear()

### PR DESCRIPTION
**Pull request by sapieneptus**
@TobiasRoikjer

### CODE REVIEW

**Comment by TobiasRoikjer** [comment]
@sapieneptus Does this invoke the same callbacks in the application?

**Comment by TobiasRoikjer** [comment]
@sapieneptus And is this an issue if spelling control has been turned off?

**Comment by sapieneptus** [comment]
@TobiasRoikjer According to [Android Docs] (http://developer.android.com/reference/android/text/Editable.html#clear()), this will invoke `theEditable.replace(0, length(), "", 0, 0)`, so if the Editable has been implemented correctly it should always work. 

I believe using the `connection` is the wrong approach because it seems that when the autocorrect pane is active, the `connection` only refers to the current text token whereas the `editable` still refers to the entire editable. 

I'll try to do some validation in XTC when I have a chance. What callbacks specifically are you concerned about?

**Comment by TobiasRoikjer** [comment]
@sapieneptus All callbacks :) I don't really know why are made, but I would like for this to be identical to a user deleting the text.

**Comment by sapieneptus** [comment]
@TobiasRoikjer I think a user would understand `ClearText()` to mean "clear all the text in this textfield". The current behavior does not, but calling `clear()` on the editable seems to do that. 

I'm not sure how to verify that "all callbacks" are fired, but if it's a large concern, we could keep the all code and just add a call to `editable.clear()` (unless that would result in firing callbacks twice).

This sounds like a job for Unit Tests! But as we don't have any and I am unsure what 'all callbacks' refers to, could you at least point me to an example of a callback triggered by `connection.commitText("", 1)` ?

**Comment by sapieneptus** [comment]
@TobiasRoikjer @krukow This could be a nice easy bug fix if we can satisfactorily verify that it doesn't break anything. I'm not sure I know enough about how to check that thoroughly and would love some input.

**Comment by sapieneptus** [comment]
@krukow This wasn't on the 'This Week' list, but this could be an easy bug fix and I don't see why it should be lingering as open this long.

**Comment by krukow** [comment]
@sapieneptus I'm OK with merging but we should test this: create a small app with a callback registered and verify that callbacks get called the same way as in the previous implementation

**Comment by sapieneptus** [comment]
Going to move this to https://github.com/calabash/calabash-android-server

**Comment by sapieneptus** [comment]
Tracking [Here](https://github.com/calabash/calabash-android-server/pull/4)

**Pull request closed without merging**
