### PR TITLE
Update text_helpers.rb

### PR DESCRIPTION
**Pull request by manikandanpracto**
Added hide keyboard function and added it to enter text function. This will avoid unexpected failure. 

For example : Fill form details

Script enter text and not hide the keyword then next step will fail due to non-visibility of next element

### CODE REVIEW

**Comment by TobiasRoikjer** [comment]
Calabash already has a function to hide the keyboard `hide_soft_keyboard`.

**Comment by manikandanpracto** [comment]
Cool, but we need to add it in enter text function, if we want to fill form details like add user details, we have lot of edit text,  in this case once keyboard shown and enter text on first field, the next step i need to enter text second field so script is waiting for field and failed. I hope you understand my issue.

**Comment by TobiasRoikjer** [comment]
@manikandanpracto I understand the problem, but I suggest making a utility method that hides the keyboard afterwards in your project, rather than changing the API. I don't think hiding the keyboard after `enter_text` is necessarily bad, but we want to make the building blocks of Calabash as simple and useful as possible. The promise of `enter_text` is that it enters text into a given field, not that it hides the keyboard afterwards.

**Comment by manikandanpracto** [comment]
@TobiasRoikjer I totally agree with you, but we do have around 4 different step definitions for enter text in some cases I need to use all four different steps, so here do I need to change all four steps according to my project ?

**Comment by TobiasRoikjer** [comment]
@manikandanpracto I don't think I understand. Are you talking about Cucumber steps or Ruby methods?

If you are talking about your feature files, the Cucumber steps, then you should generally write them in BDD style, which would not normally specify the actions with such a granularity that hiding the keyboard was changing your steps.

If you are using our predefined steps - which is fine - but not necessarily recommended, as they cannot follow best BDD/Cucumber practices, then yes, you would have to write a new step with it's own step definition.

**Comment by manikandanpracto** [comment]
@TobiasRoikjer  Yes I was talking about feature file step definitions, can we add hide_soft_keyboard in our predefined step definitions it will reduce some part work and also avoid failures.

**Comment by manikandanpracto** [comment]
OK @TobiasRoikjer I am closing this PR

**Comment by TobiasRoikjer** [comment]
@manikandanpracto I don't think it will be added. We are not adding new predefined steps.

**Comment by sherbhachu** [comment]
@manikandanpracto <https://github.com/manikandanpracto>, I would say that
you would need to manage this within your own test project, perhaps
creating a more generic enter_text method in your project and then
encapsulating it as necessary.

**Pull request closed without merging**
